### ISSUE TITLE
give you some support

### ISSUE THREAD

**Issue by z2586300277** [zhengjie9510/webgis-demo#12]
Hi , I am three-cesium-examples respository author ，your project is great and you update is often, then I think you need more people know you and star to help you to openSource.

**Comment by zhengjie9510** [comment]
Thank you so much for your kind words and support!  If you have any suggestions on how I can promote the project better, feel free to reach out. Also, I would be happy to check out your “three-cesium-examples” repository and see if there’s a chance for us to support each other!
